### ISSUE TITLE
Use yarn workspaces

### ISSUE THREAD

**Issue by amaurymartiny** [amaurymartiny/cra-lerna-electron#1]
Currently, we are [explicitly](https://github.com/amaurymartiny/cra-lerna-electron/blob/master/lerna.json#L7) not using yarn workspaces.

The reason is because `electron-webpack` uses absolute paths to node_modules, but yarn workspaces hoist them into the root folder: https://github.com/electron-userland/electron-webpack/issues/56.

Yarn introduced a [nohoist](https://yarnpkg.com/blog/2018/02/15/nohoist/) option, which may solve the above issue.

**Comment by jordymeow** [comment]
Hi @amaurymartiny. Since it's very hard to find information about this, and this is closed, have you found a solution to this? I am using to use Electron with Yarn workspaces, but I am getting a lot of compilation errors, and I actually wonder if that's simply... feasible :)

**Comment by amaurymartiny** [comment]
This was a long time ago, so I don't remember well, but `amaurymartiny closed this in 3c0504f on Jun 27, 2018` follow the commit link, and you should see how it's solved.
