### ISSUE TITLE
dynamic updates to the react component is not showing

### ISSUE THREAD

**Issue by veeramarni** [amaurymartiny/cra-lerna-electron#182]
If we have way to show changes dynamically modified in the component in the electron app would be great. Right now, only way i can see changes by rerunning `yarn electron`

**Comment by amaurymartiny** [comment]
See the commands:

yarn start | Run Electron and React in dev mode, with live reload on file changes. Allows fast iterations.
-- | --

**Comment by veeramarni** [comment]
Ok thanks
