### ISSUE TITLE
This idea is very nice, but how to communicate with electron ipcRenderer?

### ISSUE THREAD

**Issue by KaivnD** [amaurymartiny/cra-lerna-electron#46]

**Comment by amaurymartiny** [comment]
This is out of scope of this minimal template.

The main idea is:
- the webpage talks to the preload script via postMessage (window.postMessage)
- the preload script talks to the main process via IPC (ipcRenderer)
- the main process (ipcMain) listens to messages from the preload script

Here's the 1st link I found on google, it does the job: https://medium.com/@henrikbjorn/electron-communicating-via-postmessage-f9a419f94bf7

Note: you might read in some places to enable `nodeIntegration: true`. That will work too, but will introduce security vector attacks in your app.

**Comment by KaivnD** [comment]
Yes, this is the way. I already make it work after open this issue, and I was thinking make a PR for this.
Since this is out of scope of the minimal template, there is no need to make a PR.

**Comment by KaivnD** [comment]
Thanks any way!

**Comment by amaurymartiny** [comment]
If you have time, I would really appreciate a small description of how you did, for future people looking at this repo. I'd like to keep it minimal, but describing in this issue might be a good idea.

**Comment by KaivnD** [comment]
Alright! I created a PR for this #47 just now. you can see the detail right there. 
It appears to me that I can't see what's the point if we don't use node integration, which can do somthing actual browser can't do, that is the different bettween web app and electron app as I see it.

**Comment by amaurymartiny** [comment]
> It appears to me that I can't see what's the point if we don't use node integration

See https://www.electronjs.org/docs/tutorial/security#isolation-for-untrusted-content.

**Comment by KaivnD** [comment]
Sorry, let me correct this.
* I said `use node integration` is mean to use the power of node to do something that actual web browser can not do, not the `nodeIntegration` prop of `BrowserWindow` instance. 
* By the way, `preload.js` can access `require` function without  `nodeIntegration`,  so `nodeIntegration` can be switch off. 
* In my early PR `nodeIntegration` is set to true because I was exploring, and I want to ` import { ipcRenderer } from 'cra-electron' ` in `cra-react`, so I set `nodeIntegration` to true, try to export `ipcRenderer` from 'cra-electron', so I think maybe I should set `nodeIntegration` to true, but didn't work out, and I find out `preload.js` may do the job, that's was a mistake.

 I update the PR just now, if someone is looking for this try #47 , that's all.
