### ISSUE TITLE
Can not package

### ISSUE THREAD

**Issue by furrybear** [amaurymartiny/cra-lerna-electron#82]
Cannot compute electron version from installed node modules

**Comment by amaurymartiny** [comment]
Repro steps? Example repo? I have no clue what you are talking about.

**Comment by furrybear** [comment]
Sorry, when I ran `yarn run package`, an error occured. The output contained the content `Cannot compute electron version from installed node modules`. Now I find it is owing to the combination of `yarn workspaces` and `electron-builder`. So I will close the issue.
